### ISSUE TITLE
Hover en botones

### ISSUE THREAD

**Issue by NatanielCZN** [Manustoteles/mercado-liebre#3]
Los botones del formulario de registro de usuario deben tener algun cambio visible al pasar el puntero por encima (como el boton de "enviar" en el formulario de login)

![image](https://github.com/Manustoteles/mercado-liebre/assets/61957095/717c0159-3776-4a16-9cde-9a5c12eb041f)

![image](https://github.com/Manustoteles/mercado-liebre/assets/61957095/125f16be-9e97-44d8-9da3-b3cb88f61cc6)

**Comment by Manustoteles** [comment]
Listo, lo tenia pero estaba en 2 segundos, ahi lo cambio y le modifique el color.-
