### ISSUE TITLE
Reducir tiempo de transicion

### ISSUE THREAD

**Issue by NatanielCZN** [Manustoteles/mercado-liebre#4]
La duracion de las transiciones de los hover son un poco altas, para comodidad del usuario estas deben ser un poco mas rapidas. Ejemplo al hacer hover sobre los iconos del footer:

![image](https://github.com/Manustoteles/mercado-liebre/assets/61957095/0d87b364-d874-4d22-a145-c2ed0259d551)

**Comment by Manustoteles** [comment]
Listo.. resuelto
